### ISSUE TITLE
Config wird nicht erzeugt

### ISSUE THREAD

**Issue by BakermanLP** [combak/Modpack-Utils#1]
Die Default Config Datei wird beim Starten nicht automatisch erzeugt. Schwer sich diese her zu leiten.

**Comment by DerOliDE** [comment]
Kein Bug, sondern ein Feature. :) Was fehlt ist noch die Wiki zur Config und die Ingame config. Bin ein Fan von nicht zugemüllten Configs, sprich steht nur drin, was auch wirklich umkonfiguriert wurde aber ja ich sehe das Problem, wenn man noch überhaupt keinen Ansatz zur Konfiguration hat.

**Comment by DerOliDE** [comment]
Bin auf die neue Annotation Config Variante von Forge umgestiegen, damit ist dann auch die Ingame Konfiguration mit der nächsten Version möglich. :)
