### ISSUE TITLE
Crash bei Bug Report Posting

### ISSUE THREAD

**Issue by BakermanLP** [combak/Modpack-Utils#2]
https://gist.github.com/BakermanLP/88221cf3c8c4bab2169e0dd63e95d580

**Comment by DerOliDE** [comment]
Hmm scheint er dependency von Unirest nicht in die jar gepackt zu haben.

**Comment by BakermanLP** [comment]
Alles easy ... Ich habe es erst mal rein gepackt ins Modpack.
